apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrator
  namespace: openshift-kube-storage-version-migrator
  labels:
    app: migrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migrator
  template:
    metadata:
      labels:
        app: migrator
    spec:
      serviceAccountName: kube-storage-version-migrator-sa
      containers:
      - name: migrator
        image: ${IMAGE}
        command:
          - /migrator
          - '--alsologtostderr'
        terminationMessagePolicy: FallbackToLogsOnError
        imagePullPolicy: Always
