apiVersion: v1
kind: Namespace
metadata:
  name: openshift-kube-storage-version-migrator
  annotations:
    workload.openshift.io/allowed: "management"
  labels:
    openshift.io/cluster-monitoring: "true"
