kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-version-migration-migrator
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "update"]
- apiGroups: ["migration.k8s.io"]
  resources: ["storageversionmigrations"]
  verbs: ["watch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-version-migration-crd-creator
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "delete", "get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-version-migration-migrator
subjects:
- kind: ServiceAccount
  name: kube-storage-version-migrator-sa
  namespace: openshift-kube-storage-version-migrator
roleRef:
  kind: ClusterRole
  name: storage-version-migration-migrator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-version-migration-crd-creator
subjects:
- kind: ServiceAccount
  name: kube-storage-version-migrator-sa
  namespace: openshift-kube-storage-version-migrator
roleRef:
  kind: ClusterRole
  name: storage-version-migration-crd-creator
  apiGroup: rbac.authorization.k8s.io
